---
   - name: Downloding the maven source file and unarchive it.
     unarchive:
        src: "{{ url }}"
        dest: "{{ install_path }}"
        owner: "{{ install_account }}"
        group: "{{ install_group }}"
        mode: "{{ mode }}"
        copy: no

   - name: Checking untar file exist or not.
     stat:
       path: "{{ install_path }}/apache-maven-{{ maven_version }}"
     register: untar

   - name: Renaming the maven directory
     shell: cp -r {{ install_path }}/apache-maven-{{ maven_version }} /opt/maven
     when: untar.stat.exists == true

   - name: Creating sym link for maven
     file:
       src: "{{ install_path }}/maven"
       dest: "{{ install_path }}"/maven.current
       owner: "{{ install_account }}"
       group: "{{ install_group }}"
       mode: "{{ mode }}"
       state: link

